language: cpp
compiler:
- gcc
os:
- linux
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
        - cmake
        - zip
        - unzip
        - gcc-5-multilib
        - g++-5-multilib
    env:
    - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
before_install:
- eval "${MATRIX_EVAL}"
install:
- wget https://github.com/gabime/spdlog/archive/v0.10.0.zip
- wget https://dev.mysql.com/get/Downloads/Connector-C/mysql-connector-c-6.1.11-linux-glibc2.12-x86_64.tar.gz
- unzip -qq v0.10.0.zip
- mv spdlog-0.10.0/include/spdlog include
- mkdir mysql
- tar -zxf mysql-connector-c-6.1.11-linux-glibc2.12-x86_64.tar.gz -C mysql --strip-components=1
script:
- sed -i "s|^SET(MYSQL64_HOME.*|SET(MYSQL64_HOME \"$PWD\/mysql\")|" build/CMakeLists.txt
- cd build
- cmake . -DCMAKE_C_FLAGS=-m64 -DCMAKE_CXX_FLAGS=-m64
- make
- mv libr3_extension_x64.so r3_extension_x64.so
- if [ ! -z "$TRAVIS_TAG" ]; then zip "R3-Extension-$TRAVIS_TAG-Linux.zip" r3_extension_x64.so;
  fi
deploy:
  provider: releases
  api_key:
    secure: zvyRO6vQXLt6pqT8aGnEb2vviRJLA74dFx8KNZ/alV4EmJNviXQkMA80/gvkjHZVMgtUosmRZPGsj19UceqBF/sAb5EhxsSXz0GCh2gA+m5wqh99e0aGEEw+HYVI7PHi0eF9Dj8jpJgQculJ0Tci7ItUU472Hfq95sHft5joiYl5YxAqwcH4mnim9riCYESYZnwCEBXukLSdGvMXh72Wgd85nGWn+8+8thlcp94yeyPcK+I43sC2UvGrf0EJdNDoZlZirdTbzb0VkEp8wi/VdltPx6eqnj17wk+nIwRgX6mf28QgDxpr45ch8Y/VpAhI7DDaIMxSYXV7rjD9pSZ6kRD5J7rvonksYDyHAXM1wIT/dmToUVAp9PNMjL379lzfKpXIy+1uA0PGsZxJhMNd7DVWF0OOgfVv5vtk3yPcp7exI3F/QRQ4sCMdIpq8BkbjGwXdOXkvLbP63YplY/ONn7px2fLhN63ZFUhHi/ZvRMbqlZs5lSdEHEYwaLAfHd9SoZOvQl/AxeS7410GJXVv7nvHcAl0jTCRMeQ1LFhGAmv6gPP1J3tfAKYjLMEcjouNX2DK39XvtL6zERo86E/2HlYBwPUws/VkFmiJAEVtyEJNmUVVOMPp52tE7U9joIzndk4kNefxuMlE5JawPkH38FjYNVezODC+21ZwtNphwgg=
  file: "R3-Extension-$TRAVIS_TAG-Linux.zip"
  on:
    repo: Raptoer/R3-Extension
    branch: data-refactor
