language: cpp
compiler:
- gcc
os:
- linux
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
        - cmake
        - zip
        - unzip
        - gcc-5-multilib
        - g++-5-multilib
    env:
    - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
before_install:
- eval "${MATRIX_EVAL}"
install:
- wget https://github.com/gabime/spdlog/archive/v0.10.0.zip
- wget https://dev.mysql.com/get/Downloads/Connector-C/mysql-connector-c-6.1.11-linux-glibc2.12-x86_64.tar.gz
- unzip -qq v0.10.0.zip
- mv spdlog-0.10.0/include/spdlog include
- mkdir mysql
- tar -zxf mysql-connector-c-6.1.11-linux-glibc2.12-x86_64.tar.gz -C mysql --strip-components=1
script:
- sed -i "s|^SET(MYSQL64_HOME.*|SET(MYSQL64_HOME \"$PWD\/mysql\")|" build/CMakeLists.txt
- cd build
- cmake . -DCMAKE_C_FLAGS=-m64 -DCMAKE_CXX_FLAGS=-m64
- make
- mv libr3_extension_x64.so r3_extension_x64.so
- if [ ! -z "$TRAVIS_TAG" ]; then zip "R3-Extension-$TRAVIS_TAG-Linux.zip" r3_extension_x64.so;
  fi
deploy:
  provider: releases
  api_key:
    secure: O8ED4a/2J0FwvLMk0Hv+/7kujTWmopJ4DcxYV0UwVM4Z/gsPRX4YivikuKH55fSGsfMFOpbH+yUhzRv4MdWYiLz3wCZwcIrQanwcQp377R6mP/zJwJ1YhfPnk+Tgf50nmgEpkYuE4dqiXOumpnCI6+Ml+Fyq0ifk3uRSb0f1btynES3ckZHwBAQ56eB54GJr4J3FPJYZMyDS2F06XIVaZL9+FZqmGqSh16tj7T04ElqYPfC2QSXY0MuGcI/GJ2Bvx2W7rrLx8UwSlGmwKLCPyauz7GLfCcKA3ReJAxxcxutgdkI3P4sQwIyEvRiPc2lYjPdZjp9OEBy/ysSl+TjRW5rx+vXzq+VkGTg7XuWnyijWddC+TqETg1xyvsxaT0sGwIX2O6Obxp0NNTWl3aUXwYQCRgTTxYdbUN7jGR0XQgN4fuL3ENPW65zsNnspTZxuG5OkglgXxZDuVFrRpe4q+DUl6WTzp8zGnqMbIFJx+yQKF93VQgJu71WtUaxs0O+5nlBz9I5d6XZfliVf4Zl16N3fuuH9v7yGtCd3QAv0Wzb41pLAf+LyVBXF5MMATmAGF3jL2LPcmJvtuOss0na/kMx2cZ36Vs4yAap/UBkdNs4JVUFFE8i9YumbKf8kBXPpSjIW/Zwe+yX8LD9PEly8wpZJ0sMUr4zfYh2MTgoRK/Q=
  file: 'R3-Extension-$TRAVIS_TAG-Linux.zip'
  skip_cleanup: true
  on:
    tags: true
