language: cpp
compiler:
  - gcc
os:
  - linux
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
            - unzip
            - gcc-5-multilib
            - g++-5-multilib
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

before_install:
  - eval "${MATRIX_EVAL}"
install:
  - wget https://github.com/gabime/spdlog/archive/v0.10.0.zip
  - wget https://dev.mysql.com/get/Downloads/Connector-C/mysql-connector-c-6.1.11-linux-glibc2.12-i686.tar.gz
  - unzip -qq v0.10.0.zip
  - mv spdlog-0.10.0/include/spdlog include
  - mkdir mysql
  - tar -zxf mysql-connector-c-6.1.11-linux-glibc2.12-i686.tar.gz -C mysql
script:
  - sed -i "s|^SET(MYSQL64_HOME.*|SET(MYSQL64_HOME \"$PWD\/mysql\/\")|" build/CMakeLists.txt
  - cd build
  - cmake . -DCMAKE_C_FLAGS=-m64 -DCMAKE_CXX_FLAGS=-m64
  - make
